Migrate `express` and `AbstractRepresentation` type from QuantumSymbolics
qojulia/QuantumInterface.jl pull request #46
Opened 2024-12-22 08:55 UTC by apkille

https://github.com/QuantumSavory/QuantumSymbolics.jl/issues/92

2024-12-22 09:47 UTC, apkille commented
Just a note: I moved
```
express(obj) = express(obj, QuantumOpticsRepr()) # The default representation
```
to here from QuantumSymbolics to avoid type piracy in QuantumSymbolics. This isn't urgent whatsoever, but I wonder how beneficial it is to have a default representation for `express`, given that the ecosystem of packages supported by QuantumInterface is growing. This might be a bad comparison, but it's kind of like if DifferentiationInterface were to make its default backend `AutoForwardDiff` because ForwardDiff.jl has been around a long time and is used by a lot of people. Those things are true and ForwardDiff.jl is quite a handy package, but there's a ton of other autodiff packages that someone might rather use instead. I think the same could be said here. It probably would be a clearer translation interface if the user always has to explicitly define what backend they want to plug into. Of course, this would be a breaking change, but I thought I should put that thought out there.

2024-12-30 18:27 UTC, apkille commented
@Krastanov

2025-01-16 16:53 UTC, Krastanov requested changes
Looks good. I posted more comments in https://github.com/QuantumSavory/QuantumSymbolics.jl/pull/93

Only other thing here: could you add a

```
"""
Some short explanation
"""
function express end
```

after a bump of the version to `0.3.x+1` I can merge this and let you finish the one in QuantumSymbolics.

Do you have merge privileges for this repo?

2025-01-16 16:58 UTC, Krastanov commented
Marking it as a draft to remove it from my review queue for now. Convert it back when ready and merge (or ping me to merge).

2025-01-16 17:34 UTC, apkille commented
@krastanov should be good to go. I don't have merge privileges for QuantumInterface.

2025-01-16 17:47 UTC, Krastanov commented
the jet errors are also on master. Could you bump the ignore count to 3. There are ways to make this more robust, but I have not had a chance to look into it yet

2025-01-16 18:30 UTC, merged

2025-01-16 18:41 UTC, Krastanov commented
Just FYI, make sure that on similar PRs in the future you use "Squash and Merge" not "Merge", to keep the git history neat and easy to review. On most of the QuantumSavory repositories that is the default, but it is not the default here.

Of course, if you have neatly separated commits in your PR, just use "Merge". For folks that like to have neat commits in their PRs, they would usually add small fixes "junk" commits, have a reminder in the commit title (e.g. `fixup: <actual title>`) and then they would use rebase+squash to clean up before merging.